services:

  server:
    image: rust
    volumes:
      - ./rust-server/:/app
      - ./layout/:/files
    entrypoint: ["/bin/sh", "-c", "/app/server.sh"]
    networks:
      - backend
    ports:
      - 80:80

  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "5743"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/

networks:
  backend:
